// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StargateAPI.Business.Data;

#nullable disable

namespace StargateAPI.Migrations
{
    [DbContext(typeof(StargateContext))]
    [Migration("20250508171432_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("StargateAPI.Business.Data.AstronautDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CareerEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CareerStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentDutyTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentRank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("AstronautDetail");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CareerStartDate = new DateTime(2010, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "Mission Commander",
                            CurrentRank = "Astronaut",
                            PersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            CareerStartDate = new DateTime(2012, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "Science Pilot",
                            CurrentRank = "Astronaut",
                            PersonId = 2
                        },
                        new
                        {
                            Id = 3,
                            CareerEndDate = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CareerStartDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "RETIRED",
                            CurrentRank = "Astronaut Candidate",
                            PersonId = 3
                        },
                        new
                        {
                            Id = 4,
                            CareerStartDate = new DateTime(2018, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "Mission Specialist",
                            CurrentRank = "Astronaut",
                            PersonId = 4
                        },
                        new
                        {
                            Id = 5,
                            CareerEndDate = new DateTime(2020, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CareerStartDate = new DateTime(2008, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "RETIRED",
                            CurrentRank = "Astronaut",
                            PersonId = 5
                        },
                        new
                        {
                            Id = 6,
                            CareerStartDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "Pilot",
                            CurrentRank = "Astronaut Candidate",
                            PersonId = 6
                        },
                        new
                        {
                            Id = 7,
                            CareerEndDate = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CareerStartDate = new DateTime(2013, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "RETIRED",
                            CurrentRank = "Astronaut",
                            PersonId = 7
                        },
                        new
                        {
                            Id = 8,
                            CareerStartDate = new DateTime(2016, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "Spacecraft Pilot",
                            CurrentRank = "Astronaut",
                            PersonId = 8
                        },
                        new
                        {
                            Id = 9,
                            CareerEndDate = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CareerStartDate = new DateTime(2009, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "RETIRED",
                            CurrentRank = "Astronaut",
                            PersonId = 9
                        },
                        new
                        {
                            Id = 10,
                            CareerStartDate = new DateTime(2020, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "Flight Engineer",
                            CurrentRank = "Astronaut Candidate",
                            PersonId = 10
                        },
                        new
                        {
                            Id = 11,
                            CareerEndDate = new DateTime(2021, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CareerStartDate = new DateTime(2011, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "RETIRED",
                            CurrentRank = "Astronaut",
                            PersonId = 11
                        },
                        new
                        {
                            Id = 12,
                            CareerStartDate = new DateTime(2014, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "Mission Specialist",
                            CurrentRank = "Astronaut",
                            PersonId = 12
                        },
                        new
                        {
                            Id = 13,
                            CareerStartDate = new DateTime(2017, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "",
                            CurrentRank = "Science Pilot",
                            PersonId = 13
                        },
                        new
                        {
                            Id = 14,
                            CareerStartDate = new DateTime(2022, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "Pilot",
                            CurrentRank = "Astronaut Candidate",
                            PersonId = 14
                        },
                        new
                        {
                            Id = 15,
                            CareerEndDate = new DateTime(2018, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CareerStartDate = new DateTime(2007, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "RETIRED",
                            CurrentRank = "Astronaut",
                            PersonId = 15
                        });
                });

            modelBuilder.Entity("StargateAPI.Business.Data.AstronautDuty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DutyEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DutyStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DutyTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("AstronautDuty");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DutyEndDate = new DateTime(2015, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2010, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Mission Commander for Apollo 11",
                            PersonId = 1,
                            Rank = "Astronaut Candidate"
                        },
                        new
                        {
                            Id = 2,
                            DutyStartDate = new DateTime(2015, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Mission Commander for ISS Expedition 42",
                            PersonId = 1,
                            Rank = "Astronaut"
                        },
                        new
                        {
                            Id = 3,
                            DutyEndDate = new DateTime(2018, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2012, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Science Pilot for Skylab 4",
                            PersonId = 2,
                            Rank = "Astronaut"
                        },
                        new
                        {
                            Id = 4,
                            DutyStartDate = new DateTime(2018, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Science Pilot for ISS Expedition 50",
                            PersonId = 2,
                            Rank = "Astronaut"
                        },
                        new
                        {
                            Id = 5,
                            DutyEndDate = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Flight Engineer for Artemis I",
                            PersonId = 3,
                            Rank = "Astronaut Candidate"
                        },
                        new
                        {
                            Id = 6,
                            DutyStartDate = new DateTime(2023, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "RETIRED",
                            PersonId = 3,
                            Rank = "Astronaut Candidate"
                        },
                        new
                        {
                            Id = 7,
                            DutyStartDate = new DateTime(2018, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Mission Specialist for STS-61",
                            PersonId = 4,
                            Rank = "Astronaut"
                        },
                        new
                        {
                            Id = 8,
                            DutyEndDate = new DateTime(2015, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2008, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Payload Commander for STS-93",
                            PersonId = 5,
                            Rank = "Astronaut"
                        },
                        new
                        {
                            Id = 9,
                            DutyEndDate = new DateTime(2020, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2015, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Payload Commander for ISS Expedition 20",
                            PersonId = 5,
                            Rank = "Astronaut"
                        },
                        new
                        {
                            Id = 10,
                            DutyStartDate = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "RETIRED",
                            PersonId = 5,
                            Rank = "Astronaut"
                        },
                        new
                        {
                            Id = 11,
                            DutyStartDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Pilot for Artemis II",
                            PersonId = 6,
                            Rank = "Astronaut Candidate"
                        },
                        new
                        {
                            Id = 12,
                            DutyEndDate = new DateTime(2018, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2013, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Science Officer for ISS Expedition 35",
                            PersonId = 7,
                            Rank = "Astronaut"
                        },
                        new
                        {
                            Id = 13,
                            DutyEndDate = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Science Officer for ISS Expedition 60",
                            PersonId = 7,
                            Rank = "Astronaut"
                        },
                        new
                        {
                            Id = 14,
                            DutyStartDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "RETIRED",
                            PersonId = 7,
                            Rank = "Astronaut"
                        },
                        new
                        {
                            Id = 15,
                            DutyStartDate = new DateTime(2016, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Spacecraft Pilot for STS-88",
                            PersonId = 8,
                            Rank = "Astronaut"
                        },
                        new
                        {
                            Id = 16,
                            DutyEndDate = new DateTime(2014, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2009, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Mission Commander for STS-107",
                            PersonId = 9,
                            Rank = "Astronaut"
                        },
                        new
                        {
                            Id = 17,
                            DutyEndDate = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Mission Commander for ISS Expedition 25",
                            PersonId = 9,
                            Rank = "Astronaut"
                        },
                        new
                        {
                            Id = 18,
                            DutyStartDate = new DateTime(2019, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "RETIRED",
                            PersonId = 9,
                            Rank = "Astronaut"
                        },
                        new
                        {
                            Id = 19,
                            DutyStartDate = new DateTime(2020, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Flight Engineer for Artemis III",
                            PersonId = 10,
                            Rank = "Astronaut Candidate"
                        },
                        new
                        {
                            Id = 20,
                            DutyEndDate = new DateTime(2016, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2011, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Payload Specialist for STS-51-L",
                            PersonId = 11,
                            Rank = "Astronaut"
                        },
                        new
                        {
                            Id = 21,
                            DutyEndDate = new DateTime(2021, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2017, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Payload Specialist for ISS Expedition 45",
                            PersonId = 11,
                            Rank = "Astronaut"
                        },
                        new
                        {
                            Id = 22,
                            DutyStartDate = new DateTime(2021, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "RETIRED",
                            PersonId = 11,
                            Rank = "Astronaut"
                        },
                        new
                        {
                            Id = 23,
                            DutyStartDate = new DateTime(2014, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Mission Specialist for STS-125",
                            PersonId = 12,
                            Rank = "Astronaut"
                        },
                        new
                        {
                            Id = 24,
                            DutyStartDate = new DateTime(2017, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "",
                            PersonId = 13,
                            Rank = "Science Pilot for Skylab 3"
                        },
                        new
                        {
                            Id = 25,
                            DutyStartDate = new DateTime(2022, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Pilot for Artemis IV",
                            PersonId = 14,
                            Rank = "Astronaut Candidate"
                        },
                        new
                        {
                            Id = 26,
                            DutyEndDate = new DateTime(2013, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2007, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Flight Engineer for ISS Expedition 15",
                            PersonId = 15,
                            Rank = "Astronaut"
                        },
                        new
                        {
                            Id = 27,
                            DutyEndDate = new DateTime(2018, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2013, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Flight Engineer for ISS Expedition 20",
                            PersonId = 15,
                            Rank = "Astronaut"
                        },
                        new
                        {
                            Id = 28,
                            DutyStartDate = new DateTime(2018, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "RETIRED",
                            PersonId = 15,
                            Rank = "Astronaut"
                        });
                });

            modelBuilder.Entity("StargateAPI.Business.Data.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chris Johnson"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Emily Carter"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Michael Brown"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sarah Wilson"
                        },
                        new
                        {
                            Id = 7,
                            Name = "David Lee"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Laura Adams"
                        },
                        new
                        {
                            Id = 9,
                            Name = "James Taylor"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Anna White"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Robert Green"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Sophia Hall"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Daniel King"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Olivia Scott"
                        },
                        new
                        {
                            Id = 15,
                            Name = "William Harris"
                        });
                });

            modelBuilder.Entity("StargateAPI.Business.Data.AstronautDetail", b =>
                {
                    b.HasOne("StargateAPI.Business.Data.Person", "Person")
                        .WithOne("AstronautDetail")
                        .HasForeignKey("StargateAPI.Business.Data.AstronautDetail", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("StargateAPI.Business.Data.AstronautDuty", b =>
                {
                    b.HasOne("StargateAPI.Business.Data.Person", "Person")
                        .WithMany("AstronautDuties")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("StargateAPI.Business.Data.Person", b =>
                {
                    b.Navigation("AstronautDetail");

                    b.Navigation("AstronautDuties");
                });
#pragma warning restore 612, 618
        }
    }
}
